export const calendarColors = [
  { name: "Turquoise", color: "#1abc9c" },
  { name: "Emerald", color: "#2ecc71" },
  { name: "PeterRiver", color: "#3498db" },
  { name: "Amethyst", color: "#9b59b6" },
  { name: "WetAsphalt", color: "#34495e" },
  { name: "GreenSea", color: "#16a085" },
  { name: "Nephritis", color: "#27ae60" },
  { name: "BelizeHole", color: "#2980b9" },
  { name: "Wisteria", color: "#8e44ad" },
  { name: "MidnightBlue", color: "#2c3e50" },
  { name: "SunFlower", color: "#f1c40f" },
  { name: "Carrot", color: "#e67e22" },
  { name: "Alizarin", color: "#e74c3c" },
  { name: "Clouds", color: "#ecf0f1" },
  { name: "Concrete", color: "#95a5a6" },
  { name: "Orange", color: "#f39c12" },
  { name: "Pumpkin", color: "#d35400" },
  { name: "Pomegranate", color: "#c0392b" },
  { name: "Silver", color: "#bdc3c7" },
  { name: "Asbestos", color: "#7f8c8d" }
];
