const calendarColors = [
  { name: "LightGreenishBlue", color: "#55efc4" },
  { name: "FadedPoster", color: "#81ecec" },
  { name: "GreenDarnerTail", color: "#74b9ff" },
  { name: "ShyMoment", color: "#a29bfe" },
  { name: "CityLights", color: "#dfe6e9" },
  { name: "MintLeaf", color: "#00b894" },
  { name: "RobinsEggBlue", color: "#00cec9" },
  { name: "ElectronBlue", color: "#0984e3" },
  { name: "ExodusFruit", color: "#6c5ce7" },
  { name: "SoothingBreeze", color: "#b2bec3" },
  { name: "SourLemon", color: "#ffeaa7" },
  { name: "FirstDate", color: "#fab1a0" },
  { name: "PinkGlamour", color: "#ff7675" },
  { name: "Pico8Pink", color: "#fd79a8" },
  { name: "AmericanRiver", color: "#636e72" },
  { name: "BrightYarrow", color: "#fdcb6e" },
  { name: "OrangeVille", color: "#e17055" },
  { name: "Chi-Gong", color: "#d63031" },
  { name: "PrunusAvium", color: "#e84393" },
];
module.exports = calendarColors;