// 로그인, 로그아웃
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOGOUT = 'LOGOUT';
export const LOAD_USER = 'LOAD_USER';

// 멤버
export const GET_MEMBER_REQUEST = 'GET_MEMBER_REQUEST';
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS';
export const GET_MEMBER_ERROR = 'GET_MEMBER_ERROR';

export const ADD_MEMBER_REQUEST = 'ADD_MEMBER_REQUEST';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_ERROR = 'ADD_MEMBER_ERROR';

export const REMOVE_MEMBER_REQUEST = 'REMOVE_MEMBER_REQUEST';
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS';
export const REMOVE_MEMBER_ERROR= 'REMOVE_MEMBER_ERROR';

export const EDIT_MEMBER = 'EDIT_MEMBER';
export const MEMBER_ERROR = 'MEMBER_ERROR';

// 스케줄
export const SET_FIXED_SCHEDULE = 'SET_FIXED_SCHEDULE';
export const GET_FIXED_SCHEDULE = 'GET_FIXED_SCHEDULE';

export const GET_SCHEDULES_REQUEST = 'GET_SCHEDULES_REQUEST';
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';
export const GET_SCHEDULES_ERROR = 'GET_SCHEDULES_ERROR';

export const UPDATE_SCHEDULE_REQUEST = 'UPDATE_SCHEDULE_REQUEST';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS';
export const UPDATE_SCHEDULE_ERROR = 'UPDATE_SCHEDULE_ERROR';

export const REMOVE_SCHEDULE_REQUEST = 'REMOVE_SCHEDULE_REQUEST';
export const REMOVE_SCHEDULE_SUCCESS = 'REMOVE_SCHEDULE_SUCCESS';
export const REMOVE_SCHEDULE_ERROR = 'REMOVE_SCHEDULE_ERROR';

export const SET_SCHEDULE_REQUEST = 'SET_SCHEDULE_REQUEST';
export const SET_SCHEDULE_SUCCESS = 'SET_SCHEDULE_SUCCESS';
export const SET_SCHEDULE_ERROR = 'SET_SCHEDULE_ERROR';

export const CREATE_ONE_SCHEDULE_REQUEST = 'CREATE_ONE_SCHEDULE_REQUEST';
export const CREATE_ONE_SCHEDULE_SUCCESS = 'CREATE_ONE_SCHEDULE_SUCCESS';
export const CREATE_ONE_SCHEDULE_ERROR = 'CREATE_ONE_SCHEDULE_ERROR';

export const SET_SCHEDULE_TARGET = 'SET_SCHEDULE_TARGET';
export const CLEAR_SELECTED_SCHEDULE = 'CLEAR_SELECTED_SCHEDULE';


// 루틴
export const GET_ROUTINES_REQUEST = 'GET_ROUTINES_REQUEST';
export const GET_ROUTINES_SUCCESS = 'GET_ROUTINES_SUCCESS';
export const GET_ROUTINES_ERROR = 'GET_ROUTINES_ERROR';

export const SAVE_ROUTINES_REQUEST = 'SAVE_ROUTINES_REQUEST';
export const SAVE_ROUTINES_SUCCESS = 'SAVE_ROUTINES_SUCCESS';
export const SAVE_ROUTINES_ERROR = 'SAVE_ROUTINES_ERROR';

export const SET_UPDATE_ROUTINES = 'SET_UPDATE_ROUTINES';

export const SET_DATE = 'SET_DATE';
export const SET_ROUTINES = 'SET_ROUTINES';
export const INSERT_COUNT = 'INSERT_COUNT';
export const DELETE_ROUTINE = 'DELETE_ROUTINE';
export const CLEAR_ROUTINE = 'CLEAR_ROUTINE';

// 회원분석

// 타겟 초기화
export const CLEAR_TARGET = 'CLEAR_TARGET';

// 에러 초기화
export const CLEAR_ERRORS = 'CLEAR_ERRORS';